import React, { useState, useEffect } from 'react';
import ChatWindow from '../components/ChatWindow';
import { API_BASE } from '../config';
import ProfileView from '../components/ProfileView';
import DocumentManager from '../components/DocumentManager';
import { 
  Database, 
  Plus, 
  FileText, 
  Calendar, 
  Info, 
  X, 
  Sparkles, 
  CheckCircle2, 
  MessageSquare, 
  Trash2, 
  User,
  Activity,
  Menu,
  Sun,
  Moon
} from 'lucide-react';

export default function Dashboard({ user, onLogout, theme, toggleTheme }) {
  const [activeView, setActiveView] = useState('chat');
  const [chatId, setChatId] = useState(null);
  const [chats, setChats] = useState([]);
  const [sidebarOpen, setSidebarOpen] = useState(false); // Mobile sidebar toggle

  // Fetch user's historical chat sessions
  const fetchChats = async () => {
    try {
      const res = await fetch(`${API_BASE}/api/chats`, {
        headers: {
          'Authorization': 'Bearer ' + localStorage.getItem("token")
        }
      });
      const data = await res.json();
      if (res.ok) {
        setChats(data || []);
        // Auto-select first chat if no chat is active
        if (data && data.length > 0 && !chatId) {
          setChatId(data[0].id);
        }
      }
    } catch (err) {
      console.error('Error loading chats:', err);
    }
  };

  useEffect(() => {
    fetchChats();
  }, []);

  // Handle "+ New Chat" button creation trigger
  const handleCreateChat = async () => {
    try {
      const timeString = new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
      const res = await fetch(`${API_BASE}/api/chats`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': 'Bearer ' + localStorage.getItem("token")
        },
        body: JSON.stringify({
          title: `Chat Session ${timeString}`
        })
      });
      if (res.ok) {
        const newChat = await res.json();
        await fetchChats();
        setChatId(newChat.id);
        setActiveView('chat');
        setSidebarOpen(false);
      }
    } catch (err) {
      console.error('Error creating chat session:', err);
    }
  };

  // Handle active session generated by ChatWindow dynamically
  const handleChatCreated = async (newChatId) => {
    await fetchChats();
    setChatId(newChatId);
  };

  // Handle deleting targeted chat session thread
  const handleDeleteChat = async (idToDelete) => {
    try {
      const res = await fetch(`${API_BASE}/api/chats/${idToDelete}`, {
        method: 'DELETE',
        headers: {
          'Authorization': 'Bearer ' + localStorage.getItem("token")
        }
      });
      if (res.ok) {
        await fetchChats();
        if (chatId === idToDelete) {
          setChatId(null);
        }
      }
    } catch (err) {
      console.error('Error deleting chat session:', err);
    }
  };

  return (
    <div className="flex flex-col lg:flex-row h-screen w-full overflow-hidden bg-[#f0f2f5] dark:bg-[#232323] text-slate-800 dark:text-slate-200 font-sans transition-colors duration-300">
      
      {/* MOBILE HEADER BAR */}
      <div className="lg:hidden flex items-center justify-between px-6 py-4 bg-white dark:bg-[#1c1c1c] border-b border-slate-200 dark:border-[#2d2d2d] flex-shrink-0">
        <div className="flex items-center gap-3">
          <div className="bg-gradient-to-tr from-brand-600 to-violet-500 p-1.5 rounded-lg flex items-center justify-center">
            <Sparkles className="w-4 h-4 text-white" />
          </div>
          <span className="font-bold text-sm text-slate-800 dark:text-white truncate max-w-[220px]">Enterprise Knowledge Assistant</span>
        </div>
        <button 
          onClick={() => setSidebarOpen(!sidebarOpen)}
          className="p-1.5 rounded bg-slate-100 dark:bg-white/5 border border-slate-200 dark:border-white/5 text-slate-600 dark:text-slate-300 hover:text-slate-900 dark:hover:text-white"
        >
          <Menu className="w-5 h-5" />
        </button>
      </div>

      {/* LEFT SIDEBAR (Desktop permanent, Mobile slideover/overlay) */}
      <div className={`
        fixed inset-y-0 left-0 z-40 lg:relative lg:z-0 lg:flex w-80 flex-col bg-slate-50 dark:bg-[#1c1c1c] border-r border-slate-200 dark:border-[#2d2d2d] h-full transition-transform duration-300 ease-in-out flex-shrink-0 backdrop-blur-md
        ${sidebarOpen ? 'translate-x-0' : '-translate-x-full lg:translate-x-0'}
      `}>
        {/* Branding Area */}
        <div className="p-6 border-b border-slate-200 dark:border-[#2d2d2d] flex items-center justify-between flex-shrink-0">
          <div className="flex items-center gap-3">
            <div className="bg-gradient-to-tr from-brand-600 to-violet-500 p-2 rounded-xl shadow-lg flex items-center justify-center">
              <Sparkles className="w-5 h-5 text-white" />
            </div>
            <div>
              <h1 className="text-lg font-bold tracking-tight text-slate-800 dark:text-white font-sans leading-tight">
                Enterprise Knowledge Assistant
              </h1>
              <p className="text-[9px] text-slate-500 dark:text-slate-400 font-mono tracking-widest uppercase">Workspace Portal</p>
            </div>
          </div>
          {/* Theme toggle + close sidebar */}
          <div className="flex items-center gap-2">
            {/* Sun/Moon Theme Toggle */}
            <button
              onClick={toggleTheme}
              title={theme === 'dark' ? 'Switch to Light Mode' : 'Switch to Dark Mode'}
              className="p-2 rounded-lg bg-slate-100 dark:bg-[#2d2d2d] border border-slate-200 dark:border-[#333333] text-slate-600 dark:text-slate-300 hover:text-slate-900 dark:hover:text-white transition-all duration-200 cursor-pointer flex items-center justify-center"
            >
              {theme === 'dark' ? (
                <Sun className="w-4 h-4 text-amber-400" />
              ) : (
                <Moon className="w-4 h-4 text-brand-400" />
              )}
            </button>
            {/* Close sidebar button on mobile */}
            <button 
              onClick={() => setSidebarOpen(false)}
              className="lg:hidden p-1 rounded hover:bg-white/5 dark:hover:bg-[#363636] text-slate-400 hover:text-white cursor-pointer"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* New Chat Button */}
        <div className="p-4 flex-shrink-0">
          <button
            onClick={handleCreateChat}
            className="w-full flex items-center justify-center gap-2 px-4 py-2.5 bg-brand-600 hover:bg-brand-500 text-white text-xs font-semibold rounded-xl shadow-md shadow-brand-500/10 hover:shadow-brand-500/20 transition-all duration-300 cursor-pointer font-sans"
          >
            <Plus className="w-4 h-4" />
            + New Chat
          </button>
        </div>

        {/* Scrollable Historical Sessions */}
        <div className="flex-1 overflow-y-auto px-4 py-2 space-y-2">
          <span className="text-[10px] font-mono tracking-wider text-slate-500 dark:text-slate-400 px-2 uppercase">Recent Sessions</span>
          {chats.length === 0 ? (
            <div className="p-6 text-center text-slate-500 dark:text-slate-400 text-xs border border-dashed border-slate-300 dark:border-white/5 rounded-xl font-sans bg-slate-100/50 dark:bg-transparent">
              No active sessions. Start a new one!
            </div>
          ) : (
            chats.map((chat) => {
              const isActive = chatId === chat.id;
              return (
                <div
                  key={chat.id}
                  onClick={() => {
                    setChatId(chat.id);
                    setActiveView('chat');
                    setSidebarOpen(false); // Close sidebar on click in mobile
                  }}
                  className={`w-full group px-3.5 py-3 rounded-xl border flex items-center justify-between transition-all duration-300 cursor-pointer select-none ${
                    isActive
                      ? 'bg-brand-600/10 dark:bg-brand-600/20 border-brand-400/40 dark:border-brand-500/30 text-brand-600 dark:text-white font-semibold'
                      : 'bg-transparent border-transparent text-slate-600 dark:text-slate-400 hover:bg-slate-200/60 dark:hover:bg-white/5 hover:text-slate-800 dark:hover:text-slate-200'
                  }`}
                >
                  <div className="flex items-center gap-2 min-w-0 flex-1">
                    <MessageSquare className="w-4 h-4 text-brand-500 dark:text-brand-400 flex-shrink-0" />
                    <span className="text-xs truncate font-sans text-left">{chat.title}</span>
                  </div>
                  <button
                    onClick={(e) => {
                      e.stopPropagation();
                      handleDeleteChat(chat.id);
                    }}
                    className="p-1 rounded text-slate-400 dark:text-slate-500 hover:text-red-500 dark:hover:text-red-400 hover:bg-slate-200 dark:hover:bg-white/5 opacity-0 group-hover:opacity-100 focus:opacity-100 transition-all cursor-pointer flex-shrink-0"
                  >
                    <Trash2 className="w-3.5 h-3.5" />
                  </button>
                </div>
              );
            })
          )}
        </div>

        {/* Lower Navigation Section */}
        <div className="p-4 border-t border-slate-200 dark:border-[#2d2d2d] bg-slate-100/50 dark:bg-[#1e1e1e]/50 space-y-1.5 flex-shrink-0">
          <button
            onClick={() => {
              setActiveView('chat');
              setSidebarOpen(false);
            }}
            className={`w-full flex items-center gap-3 px-4 py-2.5 rounded-xl text-xs transition-all duration-300 cursor-pointer font-sans ${
              activeView === 'chat'
                ? 'bg-slate-200 dark:bg-white/5 text-slate-800 dark:text-brand-300 font-semibold border border-slate-300 dark:border-white/5 shadow-sm'
                : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-slate-200'
            }`}
          >
            <MessageSquare className="w-4 h-4" />
            Chat Workspace
          </button>
          {user?.role === 'admin' && (
            <button
              onClick={() => {
                setActiveView('documents');
                setSidebarOpen(false);
              }}
              className={`w-full flex items-center gap-3 px-4 py-2.5 rounded-xl text-xs transition-all duration-300 cursor-pointer font-sans ${
                activeView === 'documents'
                  ? 'bg-slate-200 dark:bg-white/5 text-slate-800 dark:text-brand-300 font-semibold border border-slate-300 dark:border-white/5 shadow-sm'
                  : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-slate-200'
              }`}
            >
              <Database className="w-4 h-4" />
              Document Manager
            </button>
          )}
          <button
            onClick={() => {
              setActiveView('profile');
              setSidebarOpen(false);
            }}
            className={`w-full flex items-center gap-3 px-4 py-2.5 rounded-xl text-xs transition-all duration-300 cursor-pointer font-sans ${
              activeView === 'profile'
                ? 'bg-slate-200 dark:bg-white/5 text-slate-800 dark:text-brand-300 font-semibold border border-slate-300 dark:border-white/5 shadow-sm'
                : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-slate-200'
            }`}
          >
            <User className="w-4 h-4" />
            User Profile
          </button>
        </div>
      </div>

      {/* MOBILE BACKDROP OVERLAY */}
      {sidebarOpen && (
        <div 
          onClick={() => setSidebarOpen(false)}
          className="fixed inset-0 z-30 bg-slate-950/60 backdrop-blur-sm lg:hidden"
        />
      )}

      {/* MAIN CONTENT DISPLAY PANEL */}
      <div className="flex-1 overflow-hidden p-4 sm:p-6 relative">
        {activeView === 'chat' && (
          <ChatWindow chatId={chatId} onChatCreated={handleChatCreated} />
        )}
        
        {activeView === 'documents' && user?.role === 'admin' && (
          <DocumentManager user={user} />
        )}
        
        {activeView === 'profile' && (
          <ProfileView user={user} onLogout={onLogout} />
        )}
      </div>
    </div>
  );
}
