import React, { useState, useEffect } from 'react';
import ChatWindow from '../components/ChatWindow';
import ProfileView from '../components/ProfileView';
import { 
  Database, 
  Plus, 
  FileText, 
  Calendar, 
  Info, 
  X, 
  Sparkles, 
  CheckCircle2, 
  MessageSquare, 
  Trash2, 
  User,
  Activity,
  Menu
} from 'lucide-react';

export default function Dashboard({ user, onLogout }) {
  const [activeView, setActiveView] = useState('chat');
  const [chatId, setChatId] = useState(null);
  const [chats, setChats] = useState([]);
  
  const [documents, setDocuments] = useState([]);
  const [docLoading, setDocLoading] = useState(false);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [sidebarOpen, setSidebarOpen] = useState(false); // Mobile sidebar toggle
  
  // New document form state
  const [newTitle, setNewTitle] = useState('');
  const [newType, setNewType] = useState('HR Policy');
  const [newContent, setNewContent] = useState('');
  const [uploadError, setUploadError] = useState('');
  const [uploadSuccess, setUploadSuccess] = useState(false);

  // Fetch document metadata list
  const fetchDocuments = async () => {
    try {
      const res = await fetch('http://localhost:5000/api/chat/documents', {
        headers: {
          'Authorization': 'Bearer ' + localStorage.getItem("token")
        }
      });
      const data = await res.json();
      if (res.ok) {
        setDocuments(data || []);
      }
    } catch (err) {
      console.error('Error loading documents:', err);
    }
  };

  // Fetch user's historical chat sessions
  const fetchChats = async () => {
    try {
      const res = await fetch('http://localhost:5000/api/chats', {
        headers: {
          'Authorization': 'Bearer ' + localStorage.getItem("token")
        }
      });
      const data = await res.json();
      if (res.ok) {
        setChats(data || []);
        // Auto-select first chat if no chat is active
        if (data && data.length > 0 && !chatId) {
          setChatId(data[0].id);
        }
      }
    } catch (err) {
      console.error('Error loading chats:', err);
    }
  };

  useEffect(() => {
    fetchChats();
    fetchDocuments();
  }, []);

  // Handle "+ New Chat" button creation trigger
  const handleCreateChat = async () => {
    try {
      const timeString = new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
      const res = await fetch('http://localhost:5000/api/chats', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': 'Bearer ' + localStorage.getItem("token")
        },
        body: JSON.stringify({
          title: `Chat Session ${timeString}`
        })
      });
      if (res.ok) {
        const newChat = await res.json();
        await fetchChats();
        setChatId(newChat.id);
        setActiveView('chat');
        setSidebarOpen(false);
      }
    } catch (err) {
      console.error('Error creating chat session:', err);
    }
  };

  // Handle active session generated by ChatWindow dynamically
  const handleChatCreated = async (newChatId) => {
    await fetchChats();
    setChatId(newChatId);
  };

  // Handle deleting targeted chat session thread
  const handleDeleteChat = async (idToDelete) => {
    try {
      const res = await fetch(`http://localhost:5000/api/chats/${idToDelete}`, {
        method: 'DELETE',
        headers: {
          'Authorization': 'Bearer ' + localStorage.getItem("token")
        }
      });
      if (res.ok) {
        await fetchChats();
        if (chatId === idToDelete) {
          setChatId(null);
        }
      }
    } catch (err) {
      console.error('Error deleting chat session:', err);
    }
  };

  // Handle new Document Upload/Indexing
  const handleAddDocument = async (e) => {
    e.preventDefault();
    setUploadError('');
    setUploadSuccess(false);
    setDocLoading(true);

    if (!newTitle.trim() || !newContent.trim()) {
      setUploadError('Title and content are required.');
      setDocLoading(false);
      return;
    }

    try {
      const res = await fetch('http://localhost:5000/api/chat/document', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': 'Bearer ' + localStorage.getItem("token")
        },
        body: JSON.stringify({
          title: newTitle.trim(),
          type: newType,
          content: newContent.trim()
        })
      });

      const data = await res.json();

      if (!res.ok) {
        throw new Error(data.message || 'Indexing failed');
      }

      setUploadSuccess(true);
      setNewTitle('');
      setNewContent('');
      
      // Refresh documents
      await fetchDocuments();

      // Close modal after a short delay
      setTimeout(() => {
        setIsModalOpen(false);
        setUploadSuccess(false);
      }, 1500);

    } catch (err) {
      setUploadError(err.message);
    } finally {
      setDocLoading(false);
    }
  };

  return (
    <div className="flex flex-col lg:flex-row h-screen w-full overflow-hidden bg-slate-950 text-slate-100 font-sans">
      
      {/* MOBILE HEADER BAR */}
      <div className="lg:hidden flex items-center justify-between px-6 py-4 bg-slate-900 border-b border-white/5 flex-shrink-0">
        <div className="flex items-center gap-3">
          <div className="bg-gradient-to-tr from-brand-600 to-violet-500 p-1.5 rounded-lg flex items-center justify-center">
            <Sparkles className="w-4 h-4 text-white" />
          </div>
          <span className="font-bold text-sm text-white">OmniSearch</span>
        </div>
        <button 
          onClick={() => setSidebarOpen(!sidebarOpen)}
          className="p-1.5 rounded bg-white/5 border border-white/5 text-slate-300 hover:text-white"
        >
          <Menu className="w-5 h-5" />
        </button>
      </div>

      {/* LEFT SIDEBAR (Desktop permanent, Mobile slideover/overlay) */}
      <div className={`
        fixed inset-y-0 left-0 z-40 lg:relative lg:z-0 lg:flex w-80 flex-col bg-slate-900/50 border-r border-white/5 h-full transition-transform duration-300 ease-in-out flex-shrink-0 backdrop-blur-md
        ${sidebarOpen ? 'translate-x-0' : '-translate-x-full lg:translate-x-0'}
      `}>
        {/* Branding Area */}
        <div className="p-6 border-b border-white/5 flex items-center justify-between flex-shrink-0">
          <div className="flex items-center gap-3">
            <div className="bg-gradient-to-tr from-brand-600 to-violet-500 p-2 rounded-xl shadow-lg flex items-center justify-center">
              <Sparkles className="w-5 h-5 text-white" />
            </div>
            <div>
              <h1 className="text-lg font-bold tracking-tight text-white font-sans">
                OmniSearch
              </h1>
              <p className="text-[9px] text-slate-400 font-mono tracking-widest uppercase">Workspace Portal</p>
            </div>
          </div>
          {/* Close sidebar button on mobile */}
          <button 
            onClick={() => setSidebarOpen(false)}
            className="lg:hidden p-1 rounded hover:bg-white/5 text-slate-400 hover:text-white cursor-pointer"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* New Chat Button */}
        <div className="p-4 flex-shrink-0">
          <button
            onClick={handleCreateChat}
            className="w-full flex items-center justify-center gap-2 px-4 py-2.5 bg-brand-600 hover:bg-brand-500 text-white text-xs font-semibold rounded-xl shadow-md shadow-brand-500/10 hover:shadow-brand-500/20 transition-all duration-300 cursor-pointer font-sans"
          >
            <Plus className="w-4 h-4" />
            + New Chat
          </button>
        </div>

        {/* Scrollable Historical Sessions */}
        <div className="flex-1 overflow-y-auto px-4 py-2 space-y-2">
          <span className="text-[10px] font-mono tracking-wider text-slate-500 uppercase px-2">Recent Sessions</span>
          {chats.length === 0 ? (
            <div className="p-6 text-center text-slate-500 text-xs border border-dashed border-white/5 rounded-xl font-sans">
              No active sessions. Start a new one!
            </div>
          ) : (
            chats.map((chat) => {
              const isActive = chatId === chat.id;
              return (
                <div
                  key={chat.id}
                  onClick={() => {
                    setChatId(chat.id);
                    setActiveView('chat');
                    setSidebarOpen(false); // Close sidebar on click in mobile
                  }}
                  className={`w-full group px-3.5 py-3 rounded-xl border flex items-center justify-between transition-all duration-300 cursor-pointer select-none ${
                    isActive
                      ? 'bg-brand-600/20 border-brand-500/30 text-white font-semibold'
                      : 'bg-white/0 border-transparent text-slate-400 hover:bg-white/5 hover:text-slate-200'
                  }`}
                >
                  <div className="flex items-center gap-2 min-w-0 flex-1">
                    <MessageSquare className="w-4 h-4 text-brand-400 flex-shrink-0" />
                    <span className="text-xs truncate font-sans text-left">{chat.title}</span>
                  </div>
                  <button
                    onClick={(e) => {
                      e.stopPropagation();
                      handleDeleteChat(chat.id);
                    }}
                    className="p-1 rounded text-slate-500 hover:text-red-400 hover:bg-white/5 opacity-0 group-hover:opacity-100 focus:opacity-100 transition-all cursor-pointer flex-shrink-0"
                  >
                    <Trash2 className="w-3.5 h-3.5" />
                  </button>
                </div>
              );
            })
          )}
        </div>

        {/* Lower Navigation Section */}
        <div className="p-4 border-t border-white/5 bg-slate-950/20 space-y-1.5 flex-shrink-0">
          <button
            onClick={() => {
              setActiveView('chat');
              setSidebarOpen(false);
            }}
            className={`w-full flex items-center gap-3 px-4 py-2.5 rounded-xl text-xs transition-all duration-300 cursor-pointer font-sans ${
              activeView === 'chat'
                ? 'bg-white/5 text-brand-300 font-semibold border border-white/5'
                : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            <MessageSquare className="w-4 h-4" />
            Chat Workspace
          </button>
          <button
            onClick={() => {
              setActiveView('documents');
              setSidebarOpen(false);
            }}
            className={`w-full flex items-center gap-3 px-4 py-2.5 rounded-xl text-xs transition-all duration-300 cursor-pointer font-sans ${
              activeView === 'documents'
                ? 'bg-white/5 text-brand-300 font-semibold border border-white/5'
                : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            <Database className="w-4 h-4" />
            Document Manager
          </button>
          <button
            onClick={() => {
              setActiveView('profile');
              setSidebarOpen(false);
            }}
            className={`w-full flex items-center gap-3 px-4 py-2.5 rounded-xl text-xs transition-all duration-300 cursor-pointer font-sans ${
              activeView === 'profile'
                ? 'bg-white/5 text-brand-300 font-semibold border border-white/5'
                : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            <User className="w-4 h-4" />
            User Profile
          </button>
        </div>
      </div>

      {/* MOBILE BACKDROP OVERLAY */}
      {sidebarOpen && (
        <div 
          onClick={() => setSidebarOpen(false)}
          className="fixed inset-0 z-30 bg-slate-950/60 backdrop-blur-sm lg:hidden"
        />
      )}

      {/* MAIN CONTENT DISPLAY PANEL */}
      <div className="flex-1 overflow-hidden p-4 sm:p-6 relative">
        {activeView === 'chat' && (
          <ChatWindow chatId={chatId} onChatCreated={handleChatCreated} />
        )}
        
        {activeView === 'documents' && (
          <div className="h-full flex flex-col bg-slate-900/40 border border-white/5 rounded-2xl p-6 overflow-hidden backdrop-blur-md">
            
            {/* Header & Actions */}
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-6 flex-shrink-0">
              <div>
                <h2 className="text-xl font-bold text-white font-sans">Document Indexing Database</h2>
                <p className="text-xs text-slate-400 mt-1">Manage, analyze and review documents stored in the company RAG vector database.</p>
              </div>
              
              <button
                onClick={() => setIsModalOpen(true)}
                className="flex items-center justify-center gap-1.5 px-4 py-2.5 bg-brand-600 hover:bg-brand-500 text-white text-xs font-semibold rounded-xl shadow-md transition-all duration-300 cursor-pointer font-sans self-start sm:self-auto"
              >
                <Plus className="w-4 h-4" />
                Index New Document
              </button>
            </div>

            {/* Quick Stats Grid */}
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-6 flex-shrink-0">
              <div className="p-4 rounded-xl bg-white/5 border border-white/5">
                <span className="text-[10px] text-slate-500 uppercase tracking-wider font-semibold">Database Status</span>
                <div className="flex items-center gap-2 mt-1">
                  <span className="w-2.5 h-2.5 rounded-full bg-emerald-500 animate-pulse"></span>
                  <span className="text-sm font-semibold text-slate-200">Online & Secured</span>
                </div>
              </div>
              <div className="p-4 rounded-xl bg-white/5 border border-white/5">
                <span className="text-[10px] text-slate-500 uppercase tracking-wider font-semibold">Vector Index Count</span>
                <span className="text-lg font-bold text-brand-300 block mt-0.5">{documents.length} Indexed</span>
              </div>
              <div className="p-4 rounded-xl bg-white/5 border border-white/5">
                <span className="text-[10px] text-slate-500 uppercase tracking-wider font-semibold">Storage Provider</span>
                <span className="text-sm font-semibold text-slate-200 block mt-1.5">PostgreSQL Vector DB</span>
              </div>
            </div>

            {/* Scrollable Document Grid */}
            <div className="flex-1 overflow-y-auto pr-1">
              {documents.length === 0 ? (
                <div className="h-full flex flex-col items-center justify-center text-center p-8 border border-dashed border-white/5 rounded-2xl text-slate-500 min-h-[300px]">
                  <Database className="w-12 h-12 text-slate-600 mb-3 animate-pulse" />
                  <h4 className="text-slate-300 font-semibold text-sm">No indexed knowledge</h4>
                  <p className="text-xs text-slate-500 mt-1 max-w-sm">Upload documentation and policies to index them in the database and unlock RAG query capabilities.</p>
                </div>
              ) : (
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {documents.map((doc) => (
                    <div 
                      key={doc.id} 
                      className="p-5 rounded-2xl bg-white/5 border border-white/5 hover:border-brand-500/30 transition-all duration-300 glass-hover flex flex-col justify-between"
                    >
                      <div className="space-y-3">
                        <div className="flex items-start justify-between gap-2.5">
                          <div className="flex items-center gap-2.5 min-w-0">
                            <FileText className="w-5 h-5 text-brand-400 flex-shrink-0" />
                            <h4 className="text-sm font-bold text-slate-200 truncate">{doc.title}</h4>
                          </div>
                          <span className="px-2 py-0.5 rounded bg-white/5 text-[9px] uppercase tracking-wide text-brand-300 border border-white/5 flex-shrink-0">
                            {doc.type}
                          </span>
                        </div>
                        <p className="text-xs text-slate-400 line-clamp-3 leading-relaxed">
                          This document has been fully tokenized, chunked, and embedded into the local vector DB for intent routing.
                        </p>
                      </div>

                      <div className="flex items-center justify-between border-t border-white/5 pt-4 mt-4 text-[10px] text-slate-500 font-mono">
                        <span className="flex items-center gap-1">
                          <Calendar className="w-3.5 h-3.5 text-slate-500" />
                          {new Date(doc.date).toLocaleDateString()}
                        </span>
                        <span>Size: {doc.charCount || 0} chars</span>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
        )}
        
        {activeView === 'profile' && (
          <ProfileView user={user} onLogout={onLogout} />
        )}
      </div>

      {/* DOCUMENT INDEX MODAL */}
      {isModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-md transition-opacity">
          
          <div className="w-full max-w-lg glass-card rounded-2xl overflow-hidden shadow-2xl relative animate-in fade-in zoom-in-95 duration-200">
            
            {/* Modal Header */}
            <div className="px-6 py-4 bg-white/5 border-b border-white/5 flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Sparkles className="w-4 h-4 text-brand-400" />
                <h3 className="font-bold text-slate-200 text-sm tracking-wide uppercase">Index New Knowledge</h3>
              </div>
              <button 
                onClick={() => setIsModalOpen(false)}
                className="p-1 rounded-lg text-slate-400 hover:text-white hover:bg-white/5 transition-colors cursor-pointer"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            {/* Modal Body */}
            <form onSubmit={handleAddDocument} className="p-6 space-y-4">
              
              {/* Feedback messages */}
              {uploadError && (
                <div className="p-3 bg-red-500/10 border border-red-500/20 rounded-xl text-xs text-red-400">
                  ⚠️ {uploadError}
                </div>
              )}

              {uploadSuccess && (
                <div className="p-3 bg-emerald-500/10 border border-emerald-500/20 rounded-xl text-xs text-emerald-400 flex items-center gap-2">
                  <CheckCircle2 className="w-4 h-4" />
                  Knowledge added and indexed successfully!
                </div>
              )}

              <div className="space-y-1.5">
                <label className="text-xs font-semibold text-slate-300">Document Title</label>
                <input
                  type="text"
                  required
                  disabled={docLoading || uploadSuccess}
                  value={newTitle}
                  onChange={(e) => setNewTitle(e.target.value)}
                  placeholder="e.g. HR-04: Remote Expense Guidelines"
                  className="w-full glass-input rounded-xl py-2.5 px-4 text-xs text-slate-100 placeholder-slate-600 focus:outline-none"
                />
              </div>

              <div className="space-y-1.5">
                <label className="text-xs font-semibold text-slate-300">Document Type</label>
                <select
                  disabled={docLoading || uploadSuccess}
                  value={newType}
                  onChange={(e) => setNewType(e.target.value)}
                  className="w-full glass-input rounded-xl py-2.5 px-4 text-xs text-slate-100 focus:outline-none bg-slate-900 cursor-pointer"
                >
                  <option value="HR Policy">HR Policy</option>
                  <option value="IT Security">IT Security</option>
                  <option value="Operations">Operations</option>
                  <option value="General Document">General Document</option>
                </select>
              </div>

              <div className="space-y-1.5">
                <label className="text-xs font-semibold text-slate-300">Document Content</label>
                <textarea
                  rows="6"
                  required
                  disabled={docLoading || uploadSuccess}
                  value={newContent}
                  onChange={(e) => setNewContent(e.target.value)}
                  placeholder="Paste or write document policies here. Include clear instructions so RAG can search it correctly..."
                  className="w-full glass-input rounded-xl py-2.5 px-4 text-xs text-slate-100 placeholder-slate-600 focus:outline-none resize-none"
                />
              </div>

              <div className="flex justify-end gap-3 pt-4 border-t border-white/5">
                <button
                  type="button"
                  onClick={() => setIsModalOpen(false)}
                  className="px-4 py-2 bg-white/5 hover:bg-white/10 text-xs font-semibold text-slate-300 rounded-lg transition-colors cursor-pointer"
                >
                  Cancel
                </button>
                
                <button
                  type="submit"
                  disabled={docLoading || uploadSuccess}
                  className="px-5 py-2 bg-brand-600 hover:bg-brand-500 disabled:opacity-50 text-white text-xs font-semibold rounded-lg shadow-md transition-all duration-300 cursor-pointer"
                >
                  {docLoading ? 'Analyzing & Embedding...' : 'Index Document'}
                </button>
              </div>

            </form>

          </div>
        </div>
      )}
    </div>
  );
}
